require 'rake/extensiontask'
require "rake/testtask"

Rake::ExtensionTask.new do |ext|
  ext.name = "dummy"
  ext.ext_dir = "ext/dummy"
  ext.lib_dir = "lib"
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
end

task :test => :compile

task :default => :test
