jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Ruby24:
          ruby.version: 2.4
        Ruby25:
          ruby.verison: 2.5
        Ruby26:
          ruby.version: 2.6
        RubyHead:
          ruby.version: ruby-head
      maxParallel: 4

    steps:
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '$(ruby.version)'

    - script: |
        if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- -y; fi
        export PATH="$HOME/.cargo/bin:$PATH"
        rustup update
      displayName: 'install rust'

    - script: |
        gem install bundler
        bundle install --retry=3 --jobs=4
      displayName: 'bundle install'

    - script: PATH="$HOME/.cargo/bin:$PATH" bundle exec rake
      displayName: 'bundle exec rake'
