(function() {var implementors = {};
implementors["libcruby_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libcruby_sys/struct.VALUE.html\" title=\"struct libcruby_sys::VALUE\">VALUE</a>",synthetic:false,types:["libcruby_sys::ruby::VALUE"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libcruby_sys/struct.ID.html\" title=\"struct libcruby_sys::ID\">ID</a>",synthetic:false,types:["libcruby_sys::ruby::ID"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libcruby_sys/struct.ANYARGS.html\" title=\"struct libcruby_sys::ANYARGS\">ANYARGS</a>&lt;T&gt;",synthetic:false,types:["libcruby_sys::ruby::ANYARGS"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libcruby_sys/struct.ruby_value_type.html\" title=\"struct libcruby_sys::ruby_value_type\">ruby_value_type</a>",synthetic:false,types:["libcruby_sys::ruby::ruby_value_type"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libcruby_sys/struct.st_retval.html\" title=\"struct libcruby_sys::st_retval\">st_retval</a>",synthetic:false,types:["libcruby_sys::st::st_retval"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
